"""
Helper functions for the amine radical-cation pipeline.

Unlike the neutral-radical pipeline (functions.py), radical cations are not
generated by abstracting a hydrogen atom -- they're generated by ionizing the
intact neutral molecule (removing one electron from the lone pair, no bond
broken). That means there is exactly ONE radical-cation species per parent
molecule (modulo conformers), so there is no per-hydrogen enumeration/split
step, and the reference charge ladder shifts from {-1, 0, +1} (anion/neutral
radical/cation) to {0, +1, +2} (neutral/radical cation/dication).

This module only adds the pieces that differ from functions.py (the FairChem
call at charge +1, the read-back of the shifted philicity ladder, and the
imaginary-mode check for the new file naming). Everything else reusable --
xtb pre-opt, GOAT conformer search, ORCA .inp submission, locked CSV
appends -- is imported directly from functions.py rather than duplicated.
"""

from __future__ import annotations

import os
import re
from pathlib import Path

from rdkit import Chem

from functions import (  # noqa: F401 (re-exported for convenience of callers)
    append_row_locked,
    append_rows_with_auto_radical_numbers_locked,
    check_normal_termination,
    convert_SMILES_to_xyzs,
    create_DFT_inp_file,
    create_goat_inp_file,
    create_sh_file,
    read_scf_energy,
    read_spin_contamination,
    run_sh_file,
    xyz_to_smiles,
)

RADICAL_CATION_STEM = "radicalcation"  # fixed identifier: one calc per molecule, no {h}H index needed

# SMARTS for N atoms that should NOT be treated as the oxidized amine site
_AMIDE_N = Chem.MolFromSmarts("[N][C]=[O,S]")


def _radical_cation_center_from_mulliken(out_file: Path, mol) -> int | None:
    """
    Parse DFT_elec_radicalcation.out and return the heavy-atom index (in mol
    WITHOUT explicit H) of the N with the highest Mulliken spin population.

    ORCA writes Mulliken populations with 0-based atom indices in the same
    order as the input xyz, which was generated by RDKit AddHs (heavy atoms
    first, H appended). So ORCA atom index k maps directly to
    mol.GetAtomWithIdx(k) for k < mol.GetNumAtoms().

    Returns None if the file is missing, unparseable, the max-spin atom is H,
    or no N has spin > 0.1 (spin too diffuse to assign unambiguously).
    """
    try:
        text = out_file.read_text()
    except Exception:
        return None

    blocks = list(re.finditer(
        r"MULLIKEN ATOMIC CHARGES AND SPIN POPULATIONS\s*\n-+\n(.*?)\nSum of atomic charges",
        text, re.S,
    ))
    if not blocks:
        return None

    atom_spins: dict[int, tuple[str, float]] = {}
    for line in blocks[-1].group(1).splitlines():
        m = re.match(r"\s*(\d+)\s+(\S+)\s*:\s*[-\d.]+\s+([-\d.]+)", line)
        if m:
            atom_spins[int(m.group(1))] = (m.group(2), float(m.group(3)))

    if not atom_spins:
        return None

    n_heavy = mol.GetNumAtoms()  # mol without explicit H; heavy atoms occupy indices 0..n_heavy-1
    n_candidates = [(idx, spin) for idx, (elem, spin) in atom_spins.items()
                    if elem == "N" and spin > 0.1 and idx < n_heavy]
    if not n_candidates:
        return None

    return max(n_candidates, key=lambda x: x[1])[0]


def neutral_to_radical_cation_smiles(neutral_smiles: str, mol_dir=None) -> str | None:
    """
    Convert a neutral amine SMILES to its radical-cation SMILES.

    Amine radical cations are formed by removing one electron from the amine N
    lone pair (no H abstraction, no bond breaking). The result has formal charge
    +1 and 1 radical electron on N, with all hydrogens intact.

    We cannot derive this from xyz_to_smiles/obabel because standard xyz files
    carry no charge/spin info — obabel returns neutral SMILES, giving
    GetNumRadicalElectrons()=0 everywhere and silently dropping the row.

    Implementation: AddHs to make implicit H explicit → set charge+1, radical=1,
    NoImplicit on N → RemoveHs → canonical SMILES. The AddHs step is essential:
    without it, NoImplicit removes the implicit H from the radical cation.

    When multiple aliphatic, non-amide Ns are present and mol_dir is provided,
    Mulliken spin populations from DFT_elec_radicalcation.out are used to
    identify the actual radical site. Falls back to the most-substituted-N
    heuristic (most heavy-atom neighbors) when the DFT file is unavailable or
    unparseable.

    Returns None (row is skipped) if:
      - SMILES is invalid
      - no aliphatic, non-amide, uncharged N is found
    """
    mol = Chem.MolFromSmiles(neutral_smiles)
    if mol is None:
        return None

    amide_n_idxs: set[int] = (
        {m[0] for m in mol.GetSubstructMatches(_AMIDE_N)} if _AMIDE_N else set()
    )

    amine_idxs = [
        a.GetIdx()
        for a in mol.GetAtoms()
        if a.GetSymbol() == "N"
        and not a.GetIsAromatic()
        and a.GetFormalCharge() == 0
        and a.GetIdx() not in amide_n_idxs
    ]

    if len(amine_idxs) == 0:
        return None

    if len(amine_idxs) == 1:
        chosen_idx = amine_idxs[0]
    else:
        # Try Mulliken spin from the actual DFT single point — this tells us
        # which N the radical actually sits on in the computed geometry.
        chosen_idx = None
        if mol_dir is not None:
            out_file = Path(mol_dir) / "DFT_elec_radicalcation.out"
            mulliken_idx = _radical_cation_center_from_mulliken(out_file, mol)
            if mulliken_idx is not None and mulliken_idx in amine_idxs:
                chosen_idx = mulliken_idx

        if chosen_idx is None:
            # Fall back: most substituted N (most heavy-atom neighbors)
            chosen_idx = max(amine_idxs, key=lambda i: sum(
                1 for nb in mol.GetAtomWithIdx(i).GetNeighbors() if nb.GetAtomicNum() != 1
            ))

    # AddHs first so implicit H atoms become explicit — they survive RemoveHs.
    # chosen_idx is the heavy-atom index in mol (no explicit H), which equals
    # the atom index in the AddHs mol because AddHs appends H after all heavy atoms.
    rw = Chem.RWMol(Chem.AddHs(mol))
    n_atom = rw.GetAtomWithIdx(chosen_idx)
    n_atom.SetFormalCharge(1)
    n_atom.SetNumRadicalElectrons(1)
    n_atom.SetNoImplicit(True)

    try:
        Chem.SanitizeMol(rw)
        return Chem.MolToSmiles(Chem.RemoveHs(rw))
    except Exception:
        return None


def create_fairchem_cation_sh_file(root_directory, secondary_directory, sh_file, run_file,
                                    charge=1, spinmult=2, account='tekle_smith'):
    """
    Same SLURM/FairChem invocation as functions.create_sh_file's 'fairchem'
    branch, except charge/spinmult are parameters instead of hardcoded 0/2 --
    the radical cation is optimized at charge=+1, multiplicity=2 (doublet).
    """
    root_directory = str(root_directory).rstrip("/")
    secondary_directory = str(secondary_directory).strip("/")

    workdir = Path(root_directory) / secondary_directory
    script_path = workdir / sh_file

    run_cmd = (
        "python /insomnia001/depts/tekle_smith/users/MKL/project_5/models/OMol25/cli.py "
        f'--xyz "{workdir / run_file}" --charge {charge} --spinmult {spinmult} '
        f' > "{workdir / f"fairchem_{run_file}.out"}"'
    )

    script_content = f"""#!/bin/bash

#SBATCH --account={account}
#SBATCH --job-name={secondary_directory}
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=4G
#SBATCH --time=0-2:00

export NBOEXE=/insomnia001/depts/tekle_smith/users/softwares/NBO/nbo7/bin/nbo7.i8.exe
export NBO7KEY=/insomnia001/depts/tekle_smith/users/softwares/NBO/nbo7/nbo7.key

source ~/.bashrc
conda activate fairchem

{run_cmd}
"""

    workdir.mkdir(parents=True, exist_ok=True)
    script_path.write_text(script_content)
    script_path.chmod(0o755)

    return str(script_path)


def create_readfiles_cation_sh_file(root_directory, secondary_directory, sh_file,
                                     molname, clusternum, original_smiles,
                                     batch_number, account='tekle_smith'):
    """
    Analog of functions.create_sh_file's 'readfiles' branch, but calls
    read_files_cations.py. There's no split-step SMILES to pass through here;
    read_files_cations.py derives the radical-cation SMILES from original_smiles
    via neutral_to_radical_cation_smiles (sets formal charge +1 on the amine N).
    """
    root_directory = str(root_directory).rstrip("/")
    secondary_directory = str(secondary_directory).strip("/")

    workdir = Path(root_directory) / secondary_directory
    script_path = workdir / sh_file

    run_cmd = (
        "python /insomnia001/depts/tekle_smith/users/MKL/project_5/data_generation/read_files_cations.py "
        f'--molname "{molname}" --clusternum "{clusternum}" '
        f'--original_smiles "{original_smiles}" --batch_number "{batch_number}"'
        f' > "{workdir / "read_files_cation.out"}"'
    )

    script_content = f"""#!/bin/bash

#SBATCH --account={account}
#SBATCH --job-name={secondary_directory}
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=4G
#SBATCH --time=0-2:00

export NBOEXE=/insomnia001/depts/tekle_smith/users/softwares/NBO/nbo7/bin/nbo7.i8.exe
export NBO7KEY=/insomnia001/depts/tekle_smith/users/softwares/NBO/nbo7/nbo7.key

source ~/.bashrc
conda activate chem_obabel

{run_cmd}
"""

    workdir.mkdir(parents=True, exist_ok=True)
    script_path.write_text(script_content)
    script_path.chmod(0o755)

    return str(script_path)


def create_submit_cation_pipeline_sh_file(root_directory, secondary_directory, sh_file,
                                           clusternum, original_smiles, batch_number, account='tekle_smith'):
    """SLURM wrapper that calls submit_cation_philicities.py for one molecule (post-GOAT)."""
    root_directory = str(root_directory).rstrip("/")
    secondary_directory = str(secondary_directory).strip("/")

    workdir = Path(root_directory) / secondary_directory
    script_path = workdir / sh_file

    run_cmd = (
        "python /insomnia001/depts/tekle_smith/users/MKL/project_5/data_generation/submit_cation_philicities.py "
        f'--root_directory "{root_directory}" --secondary_directory "{secondary_directory}" '
        f'--clusternum "{clusternum}" --original_smiles "{original_smiles}" --batch_number "{batch_number}" --account "{account}"'
        f' > "{workdir / "submit_cation_philicities.out"}"'
    )

    script_content = f"""#!/bin/bash

#SBATCH --account={account}
#SBATCH --job-name={secondary_directory}
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=4G
#SBATCH --time=0-2:00

export NBOEXE=/insomnia001/depts/tekle_smith/users/softwares/NBO/nbo7/bin/nbo7.i8.exe
export NBO7KEY=/insomnia001/depts/tekle_smith/users/softwares/NBO/nbo7/nbo7.key

source ~/.bashrc

{run_cmd}
"""

    workdir.mkdir(parents=True, exist_ok=True)
    script_path.write_text(script_content)
    script_path.chmod(0o755)

    return str(script_path)


def create_submit_batches_cations_sh_file(root_directory, sh_file, batch_number,
                                           account='tekle_smith', chain_id='A', max_batch=3000):
    """SLURM wrapper that chains to the next batch of submit_batches_cations.py."""
    root_directory = str(root_directory).rstrip("/")
    workdir = Path(root_directory)
    script_path = workdir / sh_file

    run_cmd = (
        "python submit_batches_cations.py "
        f'--root_directory "{root_directory}" --batch_number {batch_number} '
        f'--account "{account}" --chain_id "{chain_id}" --max_batch {max_batch}'
        f' > "{workdir / f"submit_batches_cations_{chain_id}.out"}"'
    )

    script_content = f"""#!/bin/bash

#SBATCH --account={account}
#SBATCH --job-name=submit_batches_cations
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=4G
#SBATCH --time=0-2:00

module purge
module load anaconda/2023.09
source ~/.bashrc
conda activate ~/envs/chem

{run_cmd}
"""

    workdir.mkdir(parents=True, exist_ok=True)
    script_path.write_text(script_content)
    script_path.chmod(0o755)

    return str(script_path)


def find_imaginary_nodes_cation(directory, xyz_stem=RADICAL_CATION_STEM):
    """Same check as functions.find_imaginary_nodes, for the fixed radical-cation filename."""
    filename = f"fairchem_{xyz_stem}.xyz.out"
    filepath = os.path.join(directory, filename)

    if not os.path.isfile(filepath):
        raise FileNotFoundError(f"File not found: {filepath}")

    with open(filepath, "r") as f:
        for line in f:
            if "Total imaginary modes:" in line:
                modes = int(re.search(r"(\d+)", line).group(1))
                return modes > 0

    return False


def read_philicity_cation(folder_directory):
    """
    Radical-cation analog of functions.read_philicity. The charge ladder is
    shifted up by one relative to the neutral-radical case:

        neutral radical pipeline:  anion(-1) / radical(0)  / cation(+1)
        radical cation pipeline:   neutral(0) / rad.cation(+1) / dication(+2)

    so I/A/philicity are defined the same way, just against the radical
    cation's own SCF energy instead of the neutral radical's.
    """
    neutral_scf = read_scf_energy(f'{folder_directory}/DFT_elec_neutral.out')
    radicalcation_scf = read_scf_energy(f'{folder_directory}/DFT_elec_radicalcation.out')
    dication_scf = read_scf_energy(f'{folder_directory}/DFT_elec_dication.out')

    I = (dication_scf - radicalcation_scf) * 27.2114
    A = (radicalcation_scf - neutral_scf) * 27.2114

    philicity = ((I + A) ** 2) / (I - A) * (1 / 8)

    return I, A, philicity
